import AST.AST

/-
  Semantic analysis pass: variable resolution.

  This pass traverses the AST and performs two tasks:
    1. Validates that every variable is declared before use and that no
       variable is declared twice in the same scope.
    2. Renames every local variable to a unique autogenerated name of the
       form `<original>.<counter>` (e.g. `a` → `a.0`, `b` → `b.1`).
       Autogenerated names contain a period, which is not a valid C
       identifier character, so they cannot clash with user-defined names,
       with function names, or with the `tmp.N` temporaries produced by
       TACKY generation.

  The pass returns both the renamed program and the final counter value.
  Passing that value to TACKY generation as an initial counter ensures that
  all generated identifiers are globally unique.

  Only `Var` nodes are valid lvalues in Chapter 5.  Assignments to any
  other expression are rejected here with an error.
-/

namespace Semantics

/-- The monad used during variable resolution: state (counter) + errors. -/
private abbrev VarM := StateT Nat (Except String)

/-- Entry for a variable in the variable map.
    `renamed` is the autogenerated unique name; `fromCurrent` is `true` if
    the variable was declared in the *current* scope (as opposed to an outer
    scope).  This flag lets `resolveBlockItem` distinguish duplicate
    declarations (same scope, error) from shadowing (inner scope, allowed). -/
private structure VarEntry where
  renamed     : String
  fromCurrent : Bool

/-- Association list mapping original variable names to their `VarEntry`.
    Updated as declarations are processed left to right. -/
private abbrev VarMap := List (String × VarEntry)

/-- Allocate a fresh unique name for `original`.
    Reads the current counter, increments it, and returns `"<original>.<n>"`.
    The period ensures no clash with any valid C identifier or TACKY `tmp.N`. -/
private def makeUnique (original : String) : VarM String := do
  let n ← get
  modify (· + 1)
  return s!"{original}.{n}"

/-- Look up a variable in `varMap`, returning its autogenerated name.
    Throws an error if the variable has not been declared. -/
private def lookupVar (varMap : VarMap) (name : String) : Except String String :=
  match varMap.find? (fun p => p.1 == name) with
  | some (_, entry) => .ok entry.renamed
  | none            => .error s!"Undeclared variable '{name}'"

/-- Produce a copy of `varMap` with all `fromCurrent` flags cleared.
    Used when entering an inner compound-statement scope: variables from
    outer scopes are still visible but may be shadowed by new declarations. -/
private def copyVarMap (varMap : VarMap) : VarMap :=
  varMap.map (fun (name, entry) => (name, { entry with fromCurrent := false }))

/-- Rename all variables in an expression according to `varMap`.
    Also validates that assignments and postfix operators target a `Var` lvalue. -/
private def resolveExp (varMap : VarMap) : AST.Exp → VarM AST.Exp
  | .Constant n     => return .Constant n
  | .Var v          => do
      let renamed ← liftM (lookupVar varMap v)
      return .Var renamed
  | .Unary op e     => return .Unary op (← resolveExp varMap e)
  | .Binary op l r  => return .Binary op (← resolveExp varMap l) (← resolveExp varMap r)
  | .Assignment left right => do
      match left with
      | .Var _ => pure ()
      | _      => throw "Invalid lvalue in assignment"
      return .Assignment (← resolveExp varMap left) (← resolveExp varMap right)
  | .Conditional cond e1 e2 =>
      return .Conditional (← resolveExp varMap cond)
                          (← resolveExp varMap e1)
                          (← resolveExp varMap e2)
  | .PostfixIncr e  => do
      let e' ← resolveExp varMap e
      match e' with
      | .Var _ => return .PostfixIncr e'
      | _      => throw "Invalid lvalue in postfix increment"
  | .PostfixDecr e  => do
      let e' ← resolveExp varMap e
      match e' with
      | .Var _ => return .PostfixDecr e'
      | _      => throw "Invalid lvalue in postfix decrement"

/-
  `resolveStatement`, `resolveBlockItem`, and `resolveBlockItems` are mutually
  recursive through the `Compound` constructor: `resolveStatement` calls
  `resolveBlockItems` to process the inner block, which calls `resolveBlockItem`,
  which calls `resolveStatement` for statement items.  All three are `partial`
  to let Lean accept the definition without a structural termination proof.
-/
mutual

/-- Resolve the initial clause of a `for` loop.
    Returns the renamed clause together with an updated variable map so that
    a declared variable is visible in the condition, post-expression, and body.
    This function is part of the mutual block because it is called by
    `resolveStatement` and itself calls `resolveExp`. -/
private partial def resolveForInit (varMap : VarMap) : AST.ForInit → VarM (AST.ForInit × VarMap)
  | .InitExp eOpt => do
      let eOpt' ← eOpt.mapM (resolveExp varMap)
      return (.InitExp eOpt', varMap)
  | .InitDecl decl => do
      if varMap.any (fun p => p.1 == decl.name && p.2.fromCurrent) then
        throw s!"Duplicate variable declaration '{decl.name}'"
      let renamed ← makeUnique decl.name
      let varMap' := [(decl.name, { renamed, fromCurrent := true })] ++ varMap
      let init'   ← decl.init.mapM (resolveExp varMap')
      return (.InitDecl { name := renamed, init := init' }, varMap')

/-- Rename all variables in a statement.
    `Compound` enters a new scope by calling `copyVarMap` (clearing all
    `fromCurrent` flags) before recursing into the inner block items, so
    declarations inside the compound may shadow outer variables but may not
    duplicate other declarations in the same compound body.
    `For` similarly enters a new scope for the loop header, so a declaration
    in the init clause is visible throughout the loop but not after it. -/
private partial def resolveStatement (varMap : VarMap) : AST.Statement → VarM AST.Statement
  | .Return e     => return .Return (← resolveExp varMap e)
  | .Expression e => return .Expression (← resolveExp varMap e)
  | .If cond thenStmt elseOpt => do
      let cond' ← resolveExp varMap cond
      let then' ← resolveStatement varMap thenStmt
      match elseOpt with
      | none =>
          return .If cond' then' none
      | some elseStmt => do
          let else' ← resolveStatement varMap elseStmt
          return .If cond' then' (some else')
  | .Compound items => do
      let innerMap := copyVarMap varMap
      let items'   ← resolveBlockItems innerMap items
      return .Compound items'
  -- Chapter 8: loops — body is resolved with the current varMap (no new scope
  -- for while/do-while; for creates its own scope via resolveForInit)
  | .While cond body label => do
      let cond' ← resolveExp varMap cond
      let body' ← resolveStatement varMap body
      return .While cond' body' label
  | .DoWhile body cond label => do
      let body' ← resolveStatement varMap body
      let cond' ← resolveExp varMap cond
      return .DoWhile body' cond' label
  | .For init cond post body label => do
      -- The for-loop header introduces its own scope (like a compound statement).
      let innerMap             := copyVarMap varMap
      let (init', innerMap')   ← resolveForInit innerMap init
      let cond'                ← cond.mapM (resolveExp innerMap')
      let post'                ← post.mapM (resolveExp innerMap')
      let body'                ← resolveStatement innerMap' body
      return .For init' cond' post' body' label
  | .Break label    => return .Break label
  | .Continue label => return .Continue label
  -- Chapter 8 extra credit: switch/case/default
  | .Switch exp body label cases => do
      let exp'  ← resolveExp varMap exp
      let body' ← resolveStatement varMap body
      return .Switch exp' body' label cases
  | .Case n body label => do
      let body' ← resolveStatement varMap body
      return .Case n body' label
  | .Default body label => do
      let body' ← resolveStatement varMap body
      return .Default body' label
  | .Labeled label stmt => do
      let stmt' ← resolveStatement varMap stmt
      return .Labeled label stmt'
  | .Goto label => return .Goto label
  | .Null       => return .Null

/-- Resolve a single block item.
    For declarations: validates no duplicate in the *current* scope (checking
    the `fromCurrent` flag; shadowing an outer-scope variable is allowed),
    allocates a fresh name, updates the variable map, and resolves the optional
    initializer (using the *updated* map, so `int x = x + 1` is valid).
    For statements: resolves using the existing map.
    Returns the updated variable map alongside the renamed block item. -/
private partial def resolveBlockItem (varMap : VarMap) : AST.BlockItem → VarM (VarMap × AST.BlockItem)
  | .S stmt => do
      let stmt' ← resolveStatement varMap stmt
      return (varMap, .S stmt')
  | .D decl => do
      if varMap.any (fun p => p.1 == decl.name && p.2.fromCurrent) then
        throw s!"Duplicate variable declaration '{decl.name}'"
      let renamed ← makeUnique decl.name
      -- Prepend so that `lookupVar`'s `find?` (first match) sees the most
      -- recently declared binding first; this makes inner-scope declarations
      -- correctly shadow outer-scope ones.
      let varMap' := [(decl.name, { renamed, fromCurrent := true })] ++ varMap
      -- Process initializer with the updated map (variable is in scope).
      let init'   ← decl.init.mapM (resolveExp varMap')
      return (varMap', .D { name := renamed, init := init' })

/-- Resolve all block items in a block, threading the variable map. -/
private partial def resolveBlockItems (varMap : VarMap) : List AST.BlockItem → VarM (List AST.BlockItem)
  | []           => return []
  | item :: rest => do
      let (varMap', item') ← resolveBlockItem varMap item
      let rest'            ← resolveBlockItems varMap' rest
      return item' :: rest'

end

/-- Rename all local variables in a function definition. -/
private def resolveFunctionDef (f : AST.FunctionDef) : VarM AST.FunctionDef := do
  let body' ← resolveBlockItems [] f.body
  return { f with body := body' }

/-- Entry point for the variable resolution pass.
    Returns the renamed program together with the final counter value, which
    should be used as the initial counter for TACKY generation to prevent name
    collisions between renamed local variables and TACKY temporaries. -/
def resolveProgram (p : AST.Program) : Except String (AST.Program × Nat) := do
  match (resolveFunctionDef p.func).run 0 with
  | .error msg           => .error msg
  | .ok (func', counter) => .ok ({ p with func := func' }, counter)

end Semantics
