import AST.AST

/-
  Semantic analysis pass: identifier resolution (Chapter 9).

  This pass traverses the AST and performs:
    1. Validates that every variable and function is declared before use.
    2. Validates that function calls use function names (not variable names).
    3. Validates that variable references use variable names (not function names).
    4. Validates that assignment/increment/decrement lvalues are `Var` nodes.
    5. Validates parameter uniqueness (no duplicate param names).
    6. Validates that functions are not defined more than once.
    7. Validates argument counts at call sites.
    8. Renames every local variable to a unique autogenerated name of the
       form `<original>.<counter>` (e.g. `a` → `a.0`, `b` → `b.1`).
       Autogenerated names contain a period, which is not a valid C identifier
       character, so they cannot clash with user-defined names, with function
       names, or with the `tmp.N` temporaries produced by TACKY generation.

  The identifier map tracks both variables and functions:
    IdentInfo = Var(uniqueName) | Fun(paramCount, defined)

  The map type: `List (String × (IdentInfo × Bool))` where the Bool indicates
  "declared in current scope" (for detecting redeclarations at the same level).

  The pass returns both the renamed program and the final counter value.
  Passing that value to TACKY generation as an initial counter ensures that
  all generated identifiers are globally unique.
-/

namespace Semantics

/-- The monad used during identifier resolution: state (counter) + errors. -/
private abbrev VarM := StateT Nat (Except String)

/-- Information stored for each identifier in the map.
    `Var`: a local variable with its unique renamed name.
    `Fun`: a function with its parameter count and whether it has been defined. -/
private inductive IdentInfo where
  | Var : String → IdentInfo              -- local variable: unique name
  | Fun : Nat → Bool → IdentInfo          -- function: param count, has definition?
  deriving Repr

/-- Entry for an identifier in the identifier map.
    `info` is the identity information (variable or function).
    `fromCurrent` is `true` if the identifier was declared in the *current*
    scope (as opposed to an outer scope).  This flag lets us distinguish
    duplicate declarations (same scope, error) from shadowing (inner scope, allowed). -/
private structure IdentEntry where
  info        : IdentInfo
  fromCurrent : Bool

/-- Association list mapping original identifier names to their `IdentEntry`.
    Updated as declarations are processed left to right. -/
private abbrev IdentMap := List (String × IdentEntry)

/-- Allocate a fresh unique name for `original`.
    Reads the current counter, increments it, and returns `"<original>.<n>"`.
    The period ensures no clash with any valid C identifier or TACKY `tmp.N`. -/
private def makeUnique (original : String) : VarM String := do
  let n ← get
  modify (· + 1)
  return s!"{original}.{n}"

/-- Look up `name` in the identifier map, returning `none` if not found. -/
private def lookupIdent (identMap : IdentMap) (name : String) : Option IdentEntry :=
  match identMap.find? (fun p => p.1 == name) with
  | some (_, entry) => some entry
  | none            => none

/-- Produce a copy of `identMap` with all `fromCurrent` flags cleared.
    Used when entering an inner compound-statement scope: identifiers from
    outer scopes are still visible but may be shadowed by new declarations. -/
private def enterScope (identMap : IdentMap) : IdentMap :=
  identMap.map (fun (name, entry) => (name, { entry with fromCurrent := false }))

/-- Declare a variable in the current scope.
    Validates that no other variable or function with the same name has already
    been declared in the *current* scope.  Shadowing outer scopes is allowed.
    Allocates a fresh unique name and returns the updated map. -/
private def declareVar (identMap : IdentMap) (name : String) : VarM (IdentMap × String) := do
  -- Check for redeclaration in the same scope (fromCurrent = true)
  match lookupIdent identMap name with
  | some entry =>
    if entry.fromCurrent then
      throw s!"Duplicate declaration of '{name}' in the same scope"
    -- else: shadowing is ok
  | none => pure ()
  let renamed := ← makeUnique name
  let entry : IdentEntry := { info := .Var renamed, fromCurrent := true }
  -- Prepend so that lookupIdent's find? (first match) sees the most recent binding
  let identMap' := (name, entry) :: identMap
  return (identMap', renamed)

/-- Validate and register a function declaration in the identifier map.
    Checks compatibility with any existing entry:
    - If the existing entry is a Var, error (conflict with variable).
    - If the existing entry is a Fun with different param count, error.
    - If the existing entry is a Fun already defined, and isDef is true, error
      (function defined twice).
    - If the existing entry is a Fun with fromCurrent = true and we are at the
      same scope (e.g. two local declarations in the same function body), that
      is ok as long as they are compatible (same param count, at most one def).
    Returns the updated map. -/
private def declareFun (identMap : IdentMap) (name : String) (paramCount : Nat) (isDef : Bool)
    : VarM IdentMap := do
  match lookupIdent identMap name with
  | some { info := .Var _, fromCurrent, .. } =>
      -- Only error if the variable was declared in the CURRENT scope.
      -- A function declaration is allowed to shadow a variable from an outer scope.
      if fromCurrent then
        throw s!"'{name}' was previously declared as a variable"
      -- Outer-scope variable: shadow it by prepending a new function entry.
      let entry : IdentEntry := { info := .Fun paramCount isDef, fromCurrent := true }
      return (name, entry) :: identMap
  | some { info := .Fun existingCount existingDefined, .. } =>
      if existingCount != paramCount then
        throw s!"Conflicting declarations of '{name}': different parameter counts"
      if existingDefined && isDef then
        throw s!"Function '{name}' is defined more than once"
      -- Compatible declaration: update to record if now defined
      let newDefined := existingDefined || isDef
      -- Update (replace) existing entry
      let identMap' := identMap.map fun (n, e) =>
        if n == name then
          (n, { e with info := .Fun existingCount newDefined, fromCurrent := isDef || e.fromCurrent })
        else
          (n, e)
      return identMap'
  | none =>
      -- New entry
      let entry : IdentEntry := { info := .Fun paramCount isDef, fromCurrent := true }
      return (name, entry) :: identMap

/-- Check that a list of parameter names contains no duplicates. -/
private def checkUniqueParams (params : List String) : Except String Unit := do
  let rec check : List String → Except String Unit
    | []     => .ok ()
    | p :: rest =>
        if rest.contains p then .error s!"Duplicate parameter name '{p}'"
        else check rest
  check params

/-- Rename all variables in an expression according to `identMap`.
    Also validates that:
    - `Var(v)` references declared variables (not undeclared or function names).
    - `FunCall(f, args)` references declared functions with the correct arg count.
    - Assignments and postfix operators target `Var` lvalues. -/
private def resolveExp (identMap : IdentMap) : AST.Exp → VarM AST.Exp
  | .Constant n     => return .Constant n
  | .Var v          => do
      match lookupIdent identMap v with
      | none => throw s!"Undeclared variable '{v}'"
      | some { info := .Fun _ _, .. } => throw s!"'{v}' is a function, not a variable"
      | some { info := .Var renamed, .. } => return .Var renamed
  | .Unary op e     => return .Unary op (← resolveExp identMap e)
  | .Binary op l r  => return .Binary op (← resolveExp identMap l) (← resolveExp identMap r)
  | .Assignment left right => do
      -- The left side must be a Var node (lvalue check)
      match left with
      | .Var _ => pure ()
      | _      => throw "Invalid lvalue in assignment"
      return .Assignment (← resolveExp identMap left) (← resolveExp identMap right)
  | .Conditional cond e1 e2 =>
      return .Conditional (← resolveExp identMap cond)
                          (← resolveExp identMap e1)
                          (← resolveExp identMap e2)
  | .PostfixIncr e  => do
      let e' ← resolveExp identMap e
      match e' with
      | .Var _ => return .PostfixIncr e'
      | _      => throw "Invalid lvalue in postfix increment"
  | .PostfixDecr e  => do
      let e' ← resolveExp identMap e
      match e' with
      | .Var _ => return .PostfixDecr e'
      | _      => throw "Invalid lvalue in postfix decrement"
  | .FunCall f args => do
      -- Validate that f is a known function (not a variable)
      match lookupIdent identMap f with
      | none => throw s!"Undeclared function '{f}'"
      | some { info := .Var _, .. } => throw s!"'{f}' is a variable, not a function"
      | some { info := .Fun paramCount _, .. } =>
          if args.length != paramCount then
            throw s!"Wrong number of arguments for '{f}': expected {paramCount}, got {args.length}"
          let args' ← args.mapM (resolveExp identMap)
          return .FunCall f args'

/-
  `resolveStatement`, `resolveBlockItem`, and `resolveBlockItems` are mutually
  recursive through the `Compound` constructor: `resolveStatement` calls
  `resolveBlockItems` to process the inner block, which calls `resolveBlockItem`,
  which calls `resolveStatement` for statement items.  All three are `partial`
  to let Lean accept the definition without a structural termination proof.
-/
mutual

/-- Resolve the initial clause of a `for` loop.
    Returns the renamed clause together with an updated identifier map so that
    a declared variable is visible in the condition, post-expression, and body. -/
private partial def resolveForInit (identMap : IdentMap) : AST.ForInit → VarM (AST.ForInit × IdentMap)
  | .InitExp eOpt => do
      let eOpt' ← eOpt.mapM (resolveExp identMap)
      return (.InitExp eOpt', identMap)
  | .InitDecl decl => do
      let (identMap', renamed) ← declareVar identMap decl.name
      let init'   ← decl.init.mapM (resolveExp identMap')
      return (.InitDecl { name := renamed, init := init' }, identMap')

/-- Rename all variables in a statement.
    `Compound` enters a new scope by calling `enterScope` (clearing all
    `fromCurrent` flags) before recursing into the inner block items.
    `For` similarly enters a new scope for the loop header. -/
private partial def resolveStatement (identMap : IdentMap) : AST.Statement → VarM AST.Statement
  | .Return e     => return .Return (← resolveExp identMap e)
  | .Expression e => return .Expression (← resolveExp identMap e)
  | .If cond thenStmt elseOpt => do
      let cond' ← resolveExp identMap cond
      let then' ← resolveStatement identMap thenStmt
      match elseOpt with
      | none =>
          return .If cond' then' none
      | some elseStmt => do
          let else' ← resolveStatement identMap elseStmt
          return .If cond' then' (some else')
  | .Compound items => do
      let innerMap := enterScope identMap
      let items'   ← resolveBlockItems innerMap items
      return .Compound items'
  -- Chapter 8: loops
  | .While cond body label => do
      let cond' ← resolveExp identMap cond
      let body' ← resolveStatement identMap body
      return .While cond' body' label
  | .DoWhile body cond label => do
      let body' ← resolveStatement identMap body
      let cond' ← resolveExp identMap cond
      return .DoWhile body' cond' label
  | .For init cond post body label => do
      let innerMap             := enterScope identMap
      let (init', innerMap')   ← resolveForInit innerMap init
      let cond'                ← cond.mapM (resolveExp innerMap')
      let post'                ← post.mapM (resolveExp innerMap')
      let body'                ← resolveStatement innerMap' body
      return .For init' cond' post' body' label
  | .Break label    => return .Break label
  | .Continue label => return .Continue label
  -- Chapter 8 extra credit: switch/case/default
  | .Switch exp body label cases => do
      let exp'  ← resolveExp identMap exp
      let body' ← resolveStatement identMap body
      return .Switch exp' body' label cases
  | .Case n body label => do
      let body' ← resolveStatement identMap body
      return .Case n body' label
  | .Default body label => do
      let body' ← resolveStatement identMap body
      return .Default body' label
  | .Labeled label stmt => do
      let stmt' ← resolveStatement identMap stmt
      return .Labeled label stmt'
  | .Goto label => return .Goto label
  | .Null       => return .Null

/-- Resolve a single block item.
    For variable declarations: validates no duplicate in the current scope,
    allocates a fresh name, updates the identifier map, resolves the initializer.
    For local function declarations: validates against the global function table.
    For statements: resolves using the existing map. -/
private partial def resolveBlockItem (identMap : IdentMap) : AST.BlockItem → VarM (IdentMap × AST.BlockItem)
  | .S stmt => do
      let stmt' ← resolveStatement identMap stmt
      return (identMap, .S stmt')
  | .D decl => do
      let (identMap', renamed) ← declareVar identMap decl.name
      let init'   ← decl.init.mapM (resolveExp identMap')
      return (identMap', .D { name := renamed, init := init' })
  | .FD funDecl => do
      -- Local function declaration: validate and update identifier map.
      -- Note: local function definitions (with body) are rejected by the parser.
      liftM (checkUniqueParams funDecl.params)
      let identMap' ← declareFun identMap funDecl.name funDecl.params.length false
      -- The function declaration itself is kept as-is (no renaming of params needed
      -- since this is just a prototype with no body)
      return (identMap', .FD funDecl)

/-- Resolve all block items in a block, threading the identifier map. -/
private partial def resolveBlockItems (identMap : IdentMap) : List AST.BlockItem → VarM (List AST.BlockItem)
  | []           => return []
  | item :: rest => do
      let (identMap', item') ← resolveBlockItem identMap item
      let rest'              ← resolveBlockItems identMap' rest
      return item' :: rest'

end

/-- Rename parameters to unique names and resolve the function body.
    Parameters are added to the scope (same level as function body scope).
    Redeclaring a parameter inside the function body is an error (same scope).
    Returns the updated FunctionDef with renamed params and resolved body. -/
private def resolveFunctionDef (identMap : IdentMap) (f : AST.FunctionDef) : VarM AST.FunctionDef := do
  -- Check for duplicate parameter names
  liftM (checkUniqueParams f.params)
  -- Add parameters to a fresh scope (clear fromCurrent from global entries)
  let innerMap := enterScope identMap
  -- Rename each parameter to a unique name and add to the scope
  let (innerMap', renamedParams) ← f.params.foldlM
    (fun (acc : IdentMap × List String) paramName => do
      let (m, names) := acc
      -- Each parameter must be unique within the parameter list (already checked above)
      -- but we still need to add it to the map and rename it
      let renamed ← makeUnique paramName
      let entry : IdentEntry := { info := .Var renamed, fromCurrent := true }
      let m' := (paramName, entry) :: m
      return (m', names ++ [renamed]))
    (innerMap, [])
  -- Resolve the body using the map that includes parameters
  let body' ← resolveBlockItems innerMap' f.body
  return { f with params := renamedParams, body := body' }

/-- Process a single top-level item, updating the global identifier map.
    - FunDecl: validate params, register in map as undeclared function.
    - FunDef: validate params, register in map as defined function, resolve body. -/
private def resolveTopLevel (identMap : IdentMap) : AST.TopLevel → VarM (IdentMap × AST.TopLevel)
  | .FunDecl fd => do
      liftM (checkUniqueParams fd.params)
      let identMap' ← declareFun identMap fd.name fd.params.length false
      return (identMap', .FunDecl fd)
  | .FunDef fd => do
      -- Register this function as defined in the global map
      let identMap' ← declareFun identMap fd.name fd.params.length true
      -- Resolve the function body
      let fd' ← resolveFunctionDef identMap' fd
      return (identMap', .FunDef fd')

/-- Entry point for the identifier resolution pass.
    Returns the renamed program together with the final counter value, which
    should be used as the initial counter for TACKY generation to prevent name
    collisions between renamed local variables and TACKY temporaries. -/
def resolveProgram (p : AST.Program) : Except String (AST.Program × Nat) := do
  -- Process all top-level items sequentially, threading the identifier map.
  -- The map is global: declarations/definitions are visible to subsequent items.
  let action : VarM AST.Program := do
    let (_, topLevels') ← p.topLevels.foldlM
      (fun (acc : IdentMap × List AST.TopLevel) item => do
        let (m, items) := acc
        let (m', item') ← resolveTopLevel m item
        return (m', items ++ [item']))
      ([], [])
    return { topLevels := topLevels' }
  match action.run 0 with
  | .error msg           => .error msg
  | .ok (prog', counter) => .ok (prog', counter)

end Semantics
